### ISSUE TITLE
On text search page have the results show only active facilities by default

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-omrr-transparency#84]
_Note: MVP task moved over from previous requirements document._

#### Description:

On text search page have the results show only **_active_** facilities by default

#### Definition of Ready:

- [ ] User role and type are identified
- [ ] Wireframes completed
- [x] Design / Solution is accepted by Product Owner

**Comment by mishraomp** [comment]
https://github.com/bcgov/nr-omrr-transparency/pull/72

**Comment by dawnbcgov** [comment]
Closed by #72
